[package]
name = "moon_unit"
version = "0.1.0"
authors = ["Richard Walters <rwalters@digitalstirling.com>"]
edition = "2018"

[dependencies]
mlua = { git = "https://github.com/rhymu8354/mlua.git", features = [ "lua53", "vendored" ] }
structopt = "0.3"
