/**
 * @file Runner.hpp
 *
 * This module declares the Runner class.
 *
 * © 2019 by Richard Walters
 */

#include <memory>
#include <string>
#include <vector>

/**
 * This class encapsulates all the details concerned with executing Lua
 * unit tests.
 */
class Runner {
    // Lifecycle Methods
public:
    ~Runner() noexcept;
    Runner(const Runner&) = delete;
    Runner(Runner&&) noexcept;
    Runner& operator=(const Runner&) = delete;
    Runner& operator=(Runner&&) noexcept;

    // Public Methods
public:
    /**
     * This is the constructor of the class.
     */
    Runner();

    /**
     * Execute the given Lua script.
     *
     * @param[in] fileName
     *     This is the name of the Lua script to execute.
     *
     * @param[in] script
     *     This is the contents Lua script to execute.
     *
     * @return
     *     If there is an error generated by executing the script,
     *     a description of the error is returned.  Otherwise, an
     *     empty string is returned, indicating success.
     */
    std::string LoadScript(
        const std::string& fileName,
        const std::string& script
    );

    /**
     * Return the names of all Lua tests found.
     *
     * @return
     *     The collection of names of Lua tests found is returned.
     */
    std::vector< std::string > GetTestNames() const;

    /**
     * Return a report, conforming to the report output of Google Test,
     * that provides details about the tests found and/or run.
     *
     * @return
     *     A report, conforming to the report output of Google Test,
     *     that provides details about the tests found and/or run is returned.
     */
    std::string GetReport() const;

    /**
     * Execute the Lua test with the given name.
     *
     * Any problems with the test will be reported to the standard error
     * stream.
     *
     * @param[in] testName
     *     This is the name of the Lua test to execute.
     *
     * @return
     *     An indication of whether or not the test passed is returned.
     */
    bool RunTest(const std::string& testName);

    /**
     * Return a copy of any diagnostic messages generated by the last
     * test run.
     *
     * @return
     *     A copy of any diagnostic messages generated by the last
     *     test run is returned.
     */
    std::vector< std::string > GetLastTestDiagnostics() const;

    // Private properties
private:
    /**
     * This is the type of structure that contains the private
     * properties of the instance.  It is defined in the implementation
     * and declared here to ensure that it is scoped inside the class.
     */
    struct Impl;

    /**
     * This contains the private properties of the instance.
     */
    std::unique_ptr< Impl > impl_;
};
